function expr = x7m(t,in2,in3)
%X7M
%    EXPR = X7M(T,IN2,IN3)

%    This function was generated by the Symbolic Math Toolbox version 8.7.
%    10-May-2022 22:34:09

He = in2(6,:);
Hi = in2(2,:);
Hr = in2(4,:);
Hs = in2(5,:);
Me = in2(3,:);
Mi = in2(8,:);
Ms = in2(7,:);
param36 = in3(:,1);
param37 = in3(:,2);
param38 = in3(:,3);
param39 = in3(:,4);
param40 = in3(:,5);
param41 = in3(:,6);
param42 = in3(:,7);
t2 = He.*param41;
t3 = Hi.*param38;
t4 = He.*Me;
t5 = He.*Mi;
t6 = He.*Ms;
t7 = Me+Mi+Ms;
t8 = Hi.*Ms.*param37;
t9 = Hs.*Mi.*param36.*2.0;
t10 = He+Hi+Hr+Hs;
t11 = -t9;
t12 = 1.0./t7;
t13 = 1.0./t10;
expr = [t2;Hi.*(-1.0./2.0)+t2-t3;-t13.*(-t8+param40.*t4+param42.*t4+Hi.*Me.*param40+Hi.*Me.*param42+Hr.*Me.*param40+Hr.*Me.*param42+Hs.*Me.*param40+Hs.*Me.*param42);Hr.*(-1.0./2.0)+t3;(t12.*(t4+t5+t6+t11+Hi.*Me+Hi.*Mi+Hr.*Me+Hr.*Mi+Hi.*Ms+Hr.*Ms))./2.0;t12.*(t4+t5+t6+t11+Me.*t2.*2.0+Mi.*t2.*2.0+Ms.*t2.*2.0).*(-1.0./2.0);-t13.*(t8-He.*param39-Hi.*param39-Hr.*param39-Hs.*param39+param40.*t6+Hi.*Ms.*param40+Hr.*Ms.*param40+Hs.*Ms.*param40);Me.*param42-Mi.*param40];
